### ISSUE TITLE
Make DateInput style-able

### ISSUE THREAD

**Issue by alshain** [palantir/blueprint#1554]
### Bug report

- __Package version(s)__: core: 1.27, date: 1.22
- __Browser and OS versions__: Chrome, Win 10

#### Steps to reproduce

1. have a `<DateInput inputProps={{style: {width: 200}}} />`

#### Actual behavior

Observe how the width does not change.

#### Expected behavior

Style should be merged with the styles from InputGroup.

DateInput uses an InputGroup internally, and passes the custom styles to it.

However, InputGroup ignores them:

https://github.com/palantir/blueprint/blob/89bcf098f50fb84234f0e417ead17f8ddf2782c4/packages/core/src/components/forms/inputGroup.tsx#L78

**Comment by giladgray** [comment]
thanks for reporting @alshain, definitely a bug. should be an easy fix and we'd happily accept a PR!

**Comment by alshain** [comment]
@giladgray Okay, I implemented this.

However, would it make sense to support providing styles to both the wrapping div as well as the input?

I would probably need the ability to set custom flex styles to the wrapping div element.

Most of the props apply to the input, having a `style` and an `inputStyle` would seem to run counter to that. Maybe `style` and `wrapperStyle` or `divStyle`? Doesn't seem particularly elegant either.

**Comment by llorca** [comment]
How about `<DateInput style={...} />` for the wrapping element and `<DateInput inputProps={ style: {...} } />` for the input?

**Comment by alshain** [comment]
@llorca Sure, that would work for `DateInput`. However, to fix this issue, as originally described, I only had to adjust `InputGroup` in Core.

My previous question was also for `Inputgroup`.

**Comment by sabutterworth** [comment]
Can the commit by alshain be merged in and put on a release pretty please? I'm using the latest version 1.31.0 of @blueprintjs/core and it still isn't fixed. This is really starting to impact some of the work I am doing right now - I want to pass custom calculated height/widths using style to some of the sub-controls in various components like DateInput, TimePicker & various Labs controls... all of which use InputGroup.

Thank you kindly :-)

**Comment by giladgray** [comment]
@alshain would you be able to open a PR from your fork? I think the only necessary change is in `InputGroup`; let's not worry about `<DateInput style>`.
