### ISSUE TITLE
Table2 cells don't get re-rendered when renderer's dependencies change

### ISSUE THREAD

**Issue by N1kto** [palantir/blueprint#5285]
#### Environment

- __Package version(s)__: "@blueprintjs/table": "4.1.2",  "4.1.4"
- __Operating System__: Ubuntu 20.04
- __Browser name and version__: Chromium Version 101.0.4951.41 (64 bit), Firefox 101.0a1 (2022-05-02) (64 bit)

#### Code Sandbox

[Link](https://codesandbox.io/s/blueprint-sandbox-forked-2lxlgt?file=/src/index.tsx) to a minimal repro;

#### Steps to reproduce

1. Check any checkbox within the table body
2. Checked row gets styled "selected", but the checkbox remains unchecked
3. Resize any column or the sandbox container
4. Checkbox gets re-rendered with proper checked state

#### Actual behavior
Column cells don't get re-rendered when underlying dependencies change (`rowsSelected` in demo case).  This affects all cells in the table (e.g. if there was some batch action applied to the selected rows which resulted in other cells content change) - they also don't get re-rendered.

#### Expected behavior
Column cells should get re-rendered. If you replace `Table2` with `Table` (deprecated) component leaving the remaining code unchanged it will work as expected. We've actually discovered this bug after migrating from `Table` to `Table2`.

#### Possible solution
1. Use `Table` instead of `Table2`;
2. Set a dynamic `key` prop on `Table2` which would contain selected rows details (e.g. concatenated row numbers);

#### Other observations
Issues seems to be related to (at least) `cellRenderer` prop on `<Column />` which, when gets updated, doesn't result in column cells re-render.

**Comment by adidahiya** [comment]
@N1kto I believe this should be fixed with https://github.com/palantir/blueprint/pull/5284 and use of the `cellRendererDependencies` prop. I've backported that fix to @blueprintjs/table@4.1.5, please try that out and let me know if it fixes the issue.

**Comment by N1kto** [comment]
@adidahiya thanks a lot for quick reply. The proposed solution indeed has fixed the issue :)

I've noticed `cellRendererDependencies` prop in the sources of 4.1.2 (it was mentioned that it was experimental feature there), even tried using it, but it didn't fix the problem. Though it works well on 4.1.5.
