### ISSUE TITLE
Table doesn't pass through classes provided to its classNames prop

### ISSUE THREAD

**Issue by acolombi** [palantir/blueprint#641]
Check out https://github.com/palantir/blueprint/blob/master/packages/table/src/table.tsx#L378. It would be nice if you passed through whatever classes are provided via className

**Comment by llorca** [comment]
@gscshoyru easy fix?

**Comment by giladgray** [comment]
@gscshoyru is this fixed by #738?

**Comment by adidahiya** [comment]
@giladgray nope

**Comment by gscshoyru** [comment]
...wait, why would it not be fixed by that? It should be fixed by that.

**Comment by adidahiya** [comment]
Depends on what exactly @acolombi was asking for I guess. We still don't pass down any `className` prop provided to the top-level `<Table>` component

**Comment by gscshoyru** [comment]
Oh, I misunderstood, whoops. Thought this was a different issue. 

Still probably a relatively easy fix though.

**Comment by acolombi** [comment]
Correct. Yeah, I would imagine it's an easy fix.

**Comment by cmslewis** [comment]
@acolombi @adidahiya @gscshoyru etc. -

To clarify, what's the request here? To be able to add _different_ custom CSS classes to the table container vs. the columns, or to be able to add the same custom CSS class to the table container and the columns?

The former suggests something like:

```
className?: string; // the CSS class applied to the table container
columnClassName?: string | (columnIndex: number) => string; // the CSS class to apply to each column
```

The latter suggests something like:

```
className?: string; // the CSS class applied to both the table container and each column
```
 
Tell me if my understanding is off the mark. Also, are we respecting `this.props.className` anywhere right now? Didn't immediately see where we were using it in the code, even on the table container.

**Comment by seansfkelley** [comment]
I just ran into this issue as well. I would expect `className` to appear on [the toplevel `Table` container](https://github.com/palantir/blueprint/blob/master/packages/table/src/table.tsx#L375) and nowhere else.

**Comment by cmslewis** [comment]
I agree with @seansfkelley.

**Comment by acolombi** [comment]
Yeah, likewise.

**Comment by seansfkelley** [comment]
Thanks Chris!
